name: MindsDB workflow

on:
  push:
  pull_request:
    branches:
      - stable

jobs:

  evironment_set_up:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Initial test
      run: |
        python -V 
        
