name: MindsDB Kafka Connector image build

on:
  release:
    types: [published]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push kafka connector Docker image
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        repository: mindsdb/kafka_connector
        tag_with_ref: true
